### ISSUE TITLE
Question about new AWS Verizon locations

### ISSUE THREAD

**Issue by aint** [bra-fsn/cloudperf#3]
Hi there,

I was googling trying to find how to map new AWS Verizon locations to regions and found this repo. Could you please point me out where did you find [the mapping  for those new locations](https://github.com/bra-fsn/cloudperf/commit/43e238b22869f90bc3c09c25b6067786844ed75f#diff-3c1ff0c18d0cceb5306a13c3440e98b5R30-R33)? Also, there is `aws-cloudformation` repo which has [a different mapping](https://github.com/aws-cloudformation/cfn-python-lint/commit/2159b51d77e3d8451fecca11f1ced922eb44655c#diff-bb1e4471a27659d170daf4bbf3409144R44-R47). So, I'm wondering which one is correct.

**Comment by bra-fsn** [comment]
The method is documented here:
https://github.com/bra-fsn/cloudperf/blob/43e238b22869f90bc3c09c25b6067786844ed75f/cloudperf/providers/aws_helpers.py#L370
I've already opened a ticket to AWS to provide an API/parseable data for these, but they've closed it with "will consider this in the future".
So currently it's a manual process.
As for which one is correct, the answer might be "it depends".
On the page https://aws.amazon.com/ec2/pricing/on-demand/, these are listed as separate regions and they have different pricing from their parent region.
But they are not separate regions, but sub zones. If I would use the mapping you've linked, the region based pricing wouldn't work:
![image](https://user-images.githubusercontent.com/820331/94791857-7e32a680-03d8-11eb-952d-410b9945bd44.png)
So currently I don't see a cleaner solution.

**Comment by aint** [comment]
Thanks a lot for your detailed reply!
